#!/bin/bash

# PART 0 - PREP
# 0.1 - handle arguments
while getopts hml: opt; do 
  case "${opt}" in 
    h) cat ./helpdoc && exit 0;;
    m) minimal=true;;
    l) local=true;;
  esac 
done 

#0.2 - verify root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

#0.3 - fetch support scripts
############################
############################
############################

./optimize_mirror
#./install_software
